[tool.poetry]
name = "aiosql"
version = "3.2.0"
description = "Simple SQL in Python."
authors = ["William Vaughn <vaughnwilld@gmail.com>"]
license = "BSD-2-Clause"
repository = "https://github.com/nackjicholson/aiosql"
readme = "README.md"
keywords = ["SQL", "asyncio", "PostgreSQL", "sqlite", "psycopg2"]

[tool.poetry.dependencies]
python = "^3.6"
typing_extensions = "^3.7.4"

[tool.poetry.dev-dependencies]
black = "20.8b1"
pytest = "^5.4.3"
aiosqlite = "^0.16.0"
pytest-postgresql = "^2.5.2"
asyncpg = "^0.21.0"
pytest-asyncio = "^0.14.0"
psycopg2-binary = "^2.8.6"
mkdocs = "^1.1.2"
mkautodoc = "^0.1.0"
mypy = "^0.790"

[tool.black]
line-length = 100
target-version = ["py36"]
